#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p .build

# Regenerate the served Runtime/api.js artifact from Runtime/src/ modules —
# JSHarness reads Runtime/api.js at test runtime.
scripts/build-runtime.sh

# Doc snippet sync check — fails fast if any <!-- include: ... --> block in
# README/BELIEFS/CLAUDE has drifted from its source file.
python3 docs/sync.py --check

# The LaunchAgent template daemonctl.sh install writes must stay valid XML.
scripts/daemonctl.sh print-plist | plutil -lint -

# Derive the production source list from build.sh so we don't have to keep
# two lists in sync. Drop Sources/main.swift — Tests/main.swift replaces it
# as the entry point.
SWIFT_SOURCES=()
while IFS= read -r f; do
  [[ "$f" == "Sources/main.swift" ]] || SWIFT_SOURCES+=("$f")
done < <(awk '
  /^SWIFT_SOURCES=\(/ { in_arr=1; next }
  in_arr && /^\)/     { in_arr=0; next }
  in_arr && /Sources\// { gsub(/^[[:space:]]+|[[:space:]]+$/, ""); print }
' build.sh)

# Test files — derived by glob so a new Tests/<X>Tests.swift is picked up
# automatically. The registration trampoline below is generated from the
# `func register*Tests()` definitions, killing the old silent failure mode
# (file in TEST_SOURCES but its register call missing from main.swift →
# compiled fine, never ran). Tests/main.swift stays last as the entry point.
TEST_SOURCES=(
  Tests/Harness.swift
  Tests/JSHarness.swift
)
while IFS= read -r f; do
  TEST_SOURCES+=("$f")
done < <(ls Tests/*Tests.swift | sort)

mkdir -p .build/test-obj
REG_FILE=.build/test-obj/RegisterAll.swift
{
  echo "// generated by tests.sh — do not edit"
  echo "func __registerAllTests() {"
  grep -h -o 'func register[A-Za-z0-9]*Tests' Tests/*Tests.swift | sed 's/func /    /; s/$/()/' | sort
  echo "}"
} > "$REG_FILE"

TEST_SOURCES+=("$REG_FILE" Tests/main.swift)

C_SOURCES=(
  Sources/C/TouchEvents.c
  Sources/C/SafePredicate.m
)

# Pre-compile C / ObjC sources to .o. When the combined Swift source list
# grows past a swiftc-internal threshold (hit after Bridge was split across
# multiple BridgeXxx.swift files in 2026-06), swiftc silently drops the
# `-x c` / `-x objective-c` invocations for any .c/.m args, then ld bails
# with "unknown file type". Build.sh doesn't hit the threshold so this
# bypass is only needed for the test target. Apple-side bug.
#
# Recompile only when the source is newer than the .o (mtime gate). Avoids
# the "input file modified during the build" race swiftc raises when its
# arg files change inside one invocation — every test run was rebuilding
# the .o files and swiftc would catch them mid-compile otherwise.
mkdir -p .build/test-obj
if [[ Sources/C/TouchEvents.c -nt .build/test-obj/TouchEvents.o ]]; then
  clang -c -Wno-zero-length-array -fobjc-arc \
    -target arm64-apple-macos13.0 \
    -o .build/test-obj/TouchEvents.o Sources/C/TouchEvents.c
fi
if [[ Sources/C/SafePredicate.m -nt .build/test-obj/SafePredicate.o ]]; then
  clang -c -Wno-zero-length-array -fobjc-arc \
    -target arm64-apple-macos13.0 \
    -o .build/test-obj/SafePredicate.o Sources/C/SafePredicate.m
fi

# The -sectcreate __info_plist embed below exists because TCC SIGABRTs the
# process (not a denial) when a privacy-gated API is reached without its
# usage-description key — Bluetooth.paired() in DevicesTests killed the whole
# suite this way. Tests/Info.plist, NOT Sources/Info.plist: the test binary is
# ad-hoc signed, and claiming the daemon's bundle id from a different code
# identity can flap the daemon's TCC grants (same failure mode as the
# rebuild-kills-AX-trust issue).
swiftc \
  -o .build/stackd-tests \
  "${SWIFT_SOURCES[@]}" "${TEST_SOURCES[@]}" \
  .build/test-obj/TouchEvents.o .build/test-obj/SafePredicate.o \
  -import-objc-header Sources/C/StackdBridge.h \
  -Xcc -Wno-zero-length-array \
  -Xlinker -sectcreate \
  -Xlinker __TEXT \
  -Xlinker __info_plist \
  -Xlinker Tests/Info.plist \
  -framework AppKit \
  -framework AVFoundation \
  -framework Carbon \
  -framework CoreLocation \
  -framework CoreVideo \
  -framework DiskArbitration \
  -framework EventKit \
  -framework IOBluetooth \
  -framework IOKit \
  -framework JavaScriptCore \
  -framework MultitouchSupport \
  -framework NaturalLanguage \
  -framework OSAKit \
  -framework QuickLookThumbnailing \
  -framework ScreenCaptureKit \
  -framework Vision \
  -framework WebKit \
  -F "$(xcrun --sdk macosx --show-sdk-path)/System/Library/PrivateFrameworks" \
  -target arm64-apple-macos13.0

echo "Built .build/stackd-tests"
echo
exec .build/stackd-tests "$@"
