import Foundation

registerChannelInferenceTests()
registerBridgeJsonifyTests()
registerStackDoctorTests()
registerUpdateParserTests()
registerHostDiskIOTests()
registerBonjourTests()
registerCalendarTests()
registerSpotlightLiveTests()
registerCameraStreamTests()
registerSpeechSTTTests()
registerMenubarItemsTests()
registerAppIntentsTests()
registerPrivacyRecordingTests()
registerDisplayDDCTests()
registerTemplateEngineTests()
exit(runAll())
